plugins:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: single_quotes

RSpec/MultipleExpectations:
  Max: 10

RSpec/ExampleLength:
  Max: 15

Gemspec/DevelopmentDependencies:
  Enabled: false

Layout/HashAlignment:
  Exclude:
    - whatsapp_chat_parser.gemspec
