plugins:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: single_quotes

RSpec/MultipleExpectations:
  Max: 10

RSpec/ExampleLength:
  Max: 15

Gemspec/DevelopmentDependencies:
  Enabled: false

Layout/HashAlignment:
  Exclude:
    - whatsapp-chat-parser.gemspec

Naming/FileName:
  Exclude:
    - lib/whatsapp-chat-parser.rb
    - spec/whatsapp-chat-parser_spec.rb

RSpec/SpecFilePathFormat:
  Exclude:
    - spec/whatsapp-chat-parser_spec.rb
