plugins:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.2

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 10

RSpec/ExampleLength:
  Max: 15

Gemspec/DevelopmentDependencies:
  Enabled: false

Layout/HashAlignment:
  Exclude:
    - whatsapp_chat_parser.gemspec
